### ISSUE TITLE
Extract images

### ISSUE THREAD

**Issue by seifsallam** [tmont/audio-metadata#1]
Is there a way to extract images?

**Comment by tmont** [comment]
Not at the moment, although vorbis (ogg) files don't have an explicit way to store an image, so the UTF8-encoded image data/url will be available in the result for those cases.

For ID3, this library only supports text frames, and the embedded image support appears to be stored in the `APIC` frame, so it won't be extracted.

I'll keep this issue open, though, as that seems like a useful feature.
